version: "3.8"

services:
  security:
    build: ./security
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./security/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./security/.env.dev
    depends_on:
      - security-db
  security-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=securityuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=security

volumes:
  postgres_data:
