# Generated by Django 3.1.5 on 2021-01-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210122_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='scan',
        ),
        migrations.AddField(
            model_name='asset',
            name='scan',
            field=models.ManyToManyField(related_name='assets_scanned', to='core.Scan'),
        ),
    ]
