# Generated by Django 3.1.5 on 2021-01-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210123_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
