# Generated by Django 3.1.5 on 2021-01-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets_scanned', to='core.scan'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affected_assets', to='core.vulnerability'),
        ),
    ]
