# Generated by Django 3.1.5 on 2021-01-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210123_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='scan',
        ),
        migrations.AddField(
            model_name='scan',
            name='assets',
            field=models.ManyToManyField(to='core.Asset'),
        ),
    ]
