# Generated by Django 3.1.5 on 2021-01-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210123_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='vulnerability',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='affected_assets',
            field=models.ManyToManyField(to='core.Asset'),
        ),
    ]
