# Generated by Django 3.1.5 on 2021-01-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210124_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('FAILED', 'failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(choices=[('INFORMATION', 'information'), ('MEDIUM', 'medium'), ('HIGH', 'high'), ('LOW', 'low')], max_length=50),
        ),
    ]
